/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.furnituremanagementsystem;

/**
 *
 * @author Hp
 */
public class Salesperson extends javax.swing.JFrame {

    public Salesperson() {
        initComponents();

    }

    // Variables declaration - do not modify
    // End of variables declaration
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Salesperson().setVisible(true);
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listAllPersonalSales = new javax.swing.JToggleButton();
        logout = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        manageUserProfile = new javax.swing.JButton();
        ManageSalesOrderQuotation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salesperson Dashboard");

        listAllPersonalSales.setText("List All Personal Sales");
        listAllPersonalSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllPersonalSalesActionPerformed(evt);
            }
        });

        logout.setText("logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Salesperson Dashboard");

        manageUserProfile.setText("Manage Personal Profile");
        manageUserProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserProfileActionPerformed(evt);
            }
        });

        ManageSalesOrderQuotation.setText("Manage Sale Order Quotation");
        ManageSalesOrderQuotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSalesOrderQuotationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageUserProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ManageSalesOrderQuotation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listAllPersonalSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(manageUserProfile)
                .addGap(18, 18, 18)
                .addComponent(ManageSalesOrderQuotation)
                .addGap(18, 18, 18)
                .addComponent(listAllPersonalSales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // Close the current Administrator window
        this.dispose();
        // Open the main login page window
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void manageUserProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserProfileActionPerformed
        UserProfileManager.manageUserProfile();

    }//GEN-LAST:event_manageUserProfileActionPerformed

    private void ManageSalesOrderQuotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSalesOrderQuotationActionPerformed
        SalespersonActions.showSaleOrderQuotationDialog(this);
    }//GEN-LAST:event_ManageSalesOrderQuotationActionPerformed

    private void listAllPersonalSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllPersonalSalesActionPerformed
        // Call listAllPersonalSales() after successful login
        SalespersonActions.listAllPersonalSales(this);

    }//GEN-LAST:event_listAllPersonalSalesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageSalesOrderQuotation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton listAllPersonalSales;
    private javax.swing.JToggleButton logout;
    private javax.swing.JButton manageUserProfile;
    // End of variables declaration//GEN-END:variables
}
